# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .update_message_labels import UpdateMessageLabels


class UpdateMessageRequest(UncheckedBaseModel):
    add_labels: typing.Optional[UpdateMessageLabels] = pydantic.Field(default=None)
    """
    Label or labels to add to message.
    """

    remove_labels: typing.Optional[UpdateMessageLabels] = pydantic.Field(default=None)
    """
    Label or labels to remove from message.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
