# This file was auto-generated by Fern from our API Definition.

import typing

EventType = typing.Union[
    typing.Literal[
        "message.received",
        "message.received.spam",
        "message.received.blocked",
        "message.received.unauthenticated",
        "message.sent",
        "message.delivered",
        "message.bounced",
        "message.complained",
        "message.rejected",
        "domain.verified",
    ],
    typing.Any,
]
