# This file was auto-generated by Fern from our API Definition.

import typing

MessageReceivedEventType = typing.Union[
    typing.Literal[
        "message.received", "message.received.spam", "message.received.blocked", "message.received.unauthenticated"
    ],
    typing.Any,
]
