# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...messages.types.message import Message
from ...threads.types.thread_item import ThreadItem
from .event_id import EventId
from .message_received_event_type import MessageReceivedEventType


class MessageReceivedEvent(UncheckedBaseModel):
    """
    A message was received. Spam, blocked, and unauthenticated received-message events use the same payload shape with different `event_type` values.
    """

    type: typing.Literal["event"] = "event"
    event_type: MessageReceivedEventType
    event_id: EventId
    message: Message
    thread: ThreadItem

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
