# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...inboxes.types.inbox_id import InboxId
from ...types.organization_id import OrganizationId
from .inbox_event_id import InboxEventId
from .inbox_event_type import InboxEventType


class InboxEvent(UncheckedBaseModel):
    organization_id: OrganizationId
    pod_id: str = pydantic.Field()
    """
    ID of pod.
    """

    inbox_id: InboxId
    event_id: InboxEventId
    event_type: InboxEventType
    message_id: str = pydantic.Field()
    """
    ID of message.
    """

    label: str = pydantic.Field()
    """
    Label added or removed.
    """

    event_at: dt.datetime = pydantic.Field()
    """
    Time at which the event occurred.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Time at which the event was recorded.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
